apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      - name: php
        image: php:8.2-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "MyDBRoot123"
        - name: MYSQL_DATABASE
          value: "cloud_computing"
        - name: MYSQL_USER
          value: "php"
        - name: MYSQL_PASSWORD
          value: "php"
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      volumes:
      - name: html-volume
        hostPath:
          # Ensure that this is the actual path to your HTML files on your local machine or Kubernetes node
          path: C:\Dev\infs3208-type1\src
      - name: nginx-config-volume
        hostPath:
          # Path to the nginx config file (nginx.ini or nginx.conf)
          path: C:\Dev\infs3208-type1\srcnginx.ini
