apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      - name: php
        image: your-dockerhub-username/php:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "MyDBRoot123"
        - name: MYSQL_DATABASE
          value: "cloud_computing"
        - name: MYSQL_USER
          value: "php"
        - name: MYSQL_PASSWORD
          value: "php"
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      volumes:
      - name: html-volume
        hostPath:
          # Path to your project directory
          path: /path/to/your/html/files
      - name: nginx-config-volume
        hostPath:
          # Path to the nginx config file (nginx.ini)
          path: /path/to/your/nginx.ini
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app
