apiVersion: v1
kind: PersistentVolume
metadata:
  name: html-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/your-username/infs3208-type1/src  # Path to your application files
