apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MyDBRoot123
        - name: MYSQL_DATABASE
          value: cloud_computing
        - name: MYSQL_USER
          value: php
        - name: MYSQL_PASSWORD
          value: php
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql   # Store MySQL data in the persistent volume
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc        # Claim Persistent Volume for MySQL data

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
