apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html   # Mount source code
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf      # Use Nginx ConfigMap
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: html-pvc        # Claim the persistent volume for HTML
      - name: nginx-config
        configMap:
          name: nginx-config         # Use the ConfigMap for Nginx config

---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  type: LoadBalancer               # Use LoadBalancer to expose externally
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: mynginx
