apiVersion: apps/v1
kind: Deployment
metadata:
  name: myredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myredis
  template:
    metadata:
      labels:
        app: myredis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: myredis
spec:
  ports:
  - port: 6379
  selector:
    app: myredis
